Month 8/step 2
RUS29TAM/Stellar-Burgers-React pull request #10
Opened 2023-01-12 13:36 UTC by RUS29TAM

2023-01-12 17:01 UTC, randomroot commented on src/components/ConstructorDropzone/ConstructorDropzone.jsx
> +        } ${isHovered && !filling.length ? styles.hoveredCleanDropzone : ''}`}
🟡 **Можно улучшить:**

Для таких конструкцией с условиями в классах рассмотрите возможность использования библиотеки `clsx`, это поможет улучшить читаемость вашего кода

2023-01-12 17:02 UTC, randomroot commented on src/components/OrderDetails/OrderDetails.jsx
> +const OrderDetails = ({lastOrder}) => {
🔴 **Нужно исправить:**

Для данного компонента следует прописать его `PropTypes`

2023-01-12 17:02 UTC, randomroot commented on src/components/ListIngredients/ListIngredients.jsx
> +const ListIngredients = ({heading, list, getIngredientCount}) => {
🔴 **Нужно исправить:**

Для данного компонента следует дополнить его `PropTypes`

2023-01-12 17:02 UTC, randomroot commented on src/components/IngredientCard/IngredientCard.jsx
> +const IngredientCard = ({ingredient, getIngredientCount}) => {
🔴 **Нужно исправить:**

Для данного компонента следует дополнить его `PropTypes`

2023-01-12 17:03 UTC, randomroot commented on src/components/IngredientCard/IngredientCard.jsx
> +          <Counter count={getIngredientCount(ingredient._id)} size="default"/>}
🟡 **Можно улучшить:**

Обратите внимание, что вы производите вычисления дважды - сначала для проверки наличия элемента, а потом еще раз для счётчика. Целесообразно вычислить результат единоразово и сохранить его в константу

2023-01-12 17:04 UTC, randomroot commented on src/components/IngredientCard/IngredientCard.jsx
> +        {isIngredientDetailsPopupOpen &&
🟡 **Можно улучшить:**

JSX элементы рекомендуется оборачивать в круглые скобки в рамках таких выражений, чтобы избегать возможных проблем с автоформатированием кода (см. https://medium.com/as-a-coder/why-you-should-wrap-your-jsx-with-parentheses-d7670293e45)

2023-01-12 17:05 UTC, randomroot commented on src/components/ConstructorTotalPrice/ConstructorTotalPrice.jsx
> +          {filling.length !== 0 && bun &&
🟡 **Можно улучшить:**

Формально в задании нет запрета на отправку бургера без наполнения и только из двух булок :)

2023-01-12 17:10 UTC, randomroot commented on src/services/reducers/burgerConstructorReducer.js
> +        filling: [...state.filling.filter((element) => element.constructorId !== constructorId)],
🔴 **Нужно исправить:**

Функция `filter` согласно документации (см. https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) на выходе создает **новый** массив, поэтому ручное создание копии здесь не требуется :)

2023-01-17 13:18 UTC, RUS29TAM commented on src/components/IngredientCard/IngredientCard.jsx
> +        {isIngredientDetailsPopupOpen &&
прошу прощения, могу я задать уточняющий вопрос? так-как вся возвращаемая html - конструкция уже обернута в круглые скобки, Вы говорите об отдельном элементе `{getIngredientCount(ingredient._id) !== 0 &&
          <Counter count={getIngredientCount(ingredient._id)} size="default"/>}` его также рекомендовано оборачивать в круглые скобки?

2023-01-17 13:23 UTC, randomroot commented on src/components/IngredientCard/IngredientCard.jsx
> +        {isIngredientDetailsPopupOpen &&
Добрый день!

В данном случае имеются ввиду отдельные выражения по примеру: 

```jsx

{ isOk && (
  <Element>
    ...
  </Element>
)}

```

2023-01-17 14:11 UTC, RUS29TAM commented on src/components/ConstructorTotalPrice/ConstructorTotalPrice.jsx
> +          {filling.length !== 0 && bun &&
согласен, формально запрета нет, но при отправке заказа на сервер при условии, что пользователь просто решил поесть хлеба прилетает ошибка 400 
![image](https://user-images.githubusercontent.com/90708344/212920640-adbbe350-5d80-4221-a00f-5f7fa78dc4ef.png)

2023-01-18 14:58 UTC, randomroot requested changes
**Здравствуйте!**

Вы успешно внесли множество изменений и улучшений в ваш проект, так держать, однако остался важный момент, который следует также исправить для сдачи проекта в данном спринте:

- Согласно условия задания, **в сторе** следует хранить **объект текущего просматриваемого ингредиента**, вместо использования локального стейта. Информацию в компоненте `IngredientDetails` следует получать с помощью `useSelector`, вместо пропса.

**Хорошего вам дня и настроения!** 🐈

2023-01-18 14:58 UTC, randomroot commented on src/components/Api/Api.jsx
> +const apiUrl = 'https://norma.nomoreparties.space/api';
🟡 **Можно улучшить:**

Наименования всех констант, расположенных вне компонентов или функций, следует привести к стилю 
`UPPER_CASE`. Исключения составляют только переменные значение которых описывают `PropTypes`.

2023-01-18 21:30 UTC, RUS29TAM commented
@randomroot  Михаил, спасибо Вам большое.

2023-01-18 21:41 UTC, randomroot approved these changes
🟢 **Работа принята:**

Все необходимые правки были внесены, код улучшен согласно рекомендациям, критических замечаний больше не имеется, **так держать**👍

Отличная работа, **желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

2023-01-18 21:41 UTC, randomroot commented on src/services/reducers/IngredientDetailsReducers.js
> +  switch (action.type) {
🟡 **Можно улучшить:**

При закрытии модального окна целесообразно очищать переменную `ingredient`, чтобы не занимать лишнюю память, т.к. она более не используется:)

2023-02-14 11:09 UTC, merged