Month 9/step 1
RUS29TAM/Stellar-Burgers-React pull request #11
Opened 2023-01-31 21:51 UTC by RUS29TAM

2023-02-01 01:07 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Теперь у вас есть роутинг;
- Есть регистрация и авторизация;
- Круто что вы даёте комментарии к коду;

### **Но есть несколько замечаний, которые нужно исправить:**

- Думаю можно удалить моковые данные - `utils/data`;

- Иконка тоже должна быть выделена белым цветом) - <https://disk.yandex.com/i/akGi9uTeWtQaJA>;

- <https://disk.yandex.com/i/VX1nJLab8FguzQ> - При закрытии модального окна с деталями ингредиента, у вам не меняется url на прежний;

- <https://disk.yandex.com/i/a9FSRh5_lHRmqw> - При переходе на страницу `/profile`, если пользователь обновит страницу, то он попадает на главную, а не на страницу профиля.

- Не хватает надписи `Детали ингредиента` - <https://disk.yandex.com/i/rrpdrL64fBIgIQ>;

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

2023-02-01 01:07 UTC, ArslanDev666 commented on src/hooks/useUserController.jsx
> +    })
**Можно лучше:**

Чтобы не дублировать логику с рефреш токеном, можно сделать отдельную request функцию для таких запросов.

Например такую:
```js
export const fetchWithRefresh = async (url, options) => {
  try {
    const res = await fetch(url, options);
    return await checkReponse(res);
  } catch (err) {
    if (err.message === "jwt expired") {
      const refreshData = await refreshToken();
      if (!refreshData.success) {
        Promise.reject(refreshData);
      }
      localStorage.setItem("refreshToken", refreshData.refreshToken);
      setCookie("accessToken", refreshData.accessToken);
      options.headers.authorization = refreshData.accessToken;
      const res = await fetch(url, options);
      return await checkReponse(res);
    } else {
      return Promise.reject(err);
    }
  }
};

// Использование

const getUser = () => {
  return fetchWithRefresh(`${BURGER_API_URL}/auth/user`, {
    headers: {
      authorization: getCookie("accessToken"),
    },
  });
};
```

2023-02-01 01:07 UTC, ArslanDev666 commented on src/hooks/useUserController.jsx
> +      false
**Надо исправить:**

Используйте обычный if)

2023-02-01 01:07 UTC, ArslanDev666 commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +    cart.bun ? ingredientsCount[cart.bun._id] = 2 : false
**Надо исправить:**

Используйте обычный if)

2023-02-01 01:07 UTC, ArslanDev666 commented on src/components/Forms/FormForgotPassword/FormForgotPassword.jsx
> +      <form className={styleForgotPass.form} onSubmit={onSubmit}>
**Вы молодец!:**

Круто что вы обрабатываете отправку формы через событие `onSubmit`

2023-02-12 13:35 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец! Работа принята. Удачи в дальнейшем обучении!**

- Все замечания с прошлого ревью были исправлены.

### **Рекомендую исправить:**

- Если неавторизованный пользователь попытается перейти по этой ссылки, то он должен попадать на страницу логина, а у вас идёт бесконечный лоадинг <https://disk.yandex.com/i/VvZEB-3B3PI4yA>;

2023-02-12 19:58 UTC, RUS29TAM commented
@ArslanDev666 Большое спасибо!

2023-02-14 11:10 UTC, merged