Month 10/step 1
RUS29TAM/Stellar-Burgers-React pull request #16
Opened 2023-03-23 08:39 UTC by RUS29TAM

2023-03-23 09:10 UTC, andryxxa93 requested changes
Здравствуйте! Отличная работа! 
Что понравилось:
- Хорошо типизировали утилитарные функции
- Использовали дженерики

Что необходимо исправить:
- В проекте присутствует очень много `ts-ignore` и `any` от которых необходимо избавиться. Такие конструкции сводят на ноль типизацию и если вы часто к ним вынуждены прибегать, то это верный признак того, что с типизацией есть проблемы.
- Есть места где вы по-прежнему используете не типизированный `useSelector` - необходимо заменить на типизированный.

Напомню, что если у вас что-то не получается, то вы всегда можете обратиться к своему наставнику.

Удачных правок!

2023-03-30 05:49 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

2023-03-30 05:49 UTC, andryxxa93 commented on src/components/app-main/app-main.tsx
> +    const {loading, error} = AppSelector((store:RootState) => store.ingredients);
**Можно лучше**
Указывать `state: RootState` уже не нужно, `AppSelector` это делает за вас

2023-03-30 05:49 UTC, andryxxa93 commented on src/components/modal-ingredients-details/modal-ingredients-details.tsx
> +        // @ts-ignore
**Можно лучше**
Этот  `@ts-ignore` - тут уже не нужен - его можно удалить и так всё работает

2023-03-30 19:45 UTC, RUS29TAM commented
@andryxxa93 спасибо!

2023-03-31 07:52 UTC, merged